### PR TITLE
Editor

### PR DESCRIPTION
**Pull request by gabriel-tessier**
So far what I done.

### CODE REVIEW

**Comment by gabriel-tessier** [comment]
@leandrodamascena 
You can check here and start making changes.
it's from the branch editor.

**Comment by leandrodamascena** [comment]
Great man!! I'll clone this branch and review, ok?

**Comment by mingrammer** [comment]
I think we don't have to include all the third party css/js libraries in the repository because we can download all libraries simply by just `npm install` or `yarn install` on the machine or docker image. (like `pip install`)

Writing the documentation about installing js libraries on the README or DEVELOPMENT would be enough.

Wdyt?

**Comment by gabriel-tessier** [comment]
@mingrammer 
Good point! It will make code more light and more easy to maintain!

@leandrodamascena 
If you think same just thumb up and I'll make a new issue and work on it! 

Democracy POWAAA!

**Pull request closed without merging**
